### PR TITLE
Fixed: added contribution section to  README.md

### LINKED ISSUE #352: Feature: Adding contributors section to the README.md file.
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
contributors

### PR DESCRIPTION
**Pull request by Kalyanimhala**
Fixed #352 
Added Contribution section.
@Licenser  check and merge the PR. Thank You!

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
I like it, that's an elegant solution! 👍

**Comment by Kalyanimhala** [comment]
@Licenser Thank You!
Happy to contribute in more ways!

**Comment by Licenser** [comment]
Awesome :D 

If you want to add the same to [simd-json-derive](https://github.com/simd-lite/simd-json/simd-json-derive) and the [value-trait](https://github.com/simd-lite/simd-json/value-trait) I'd gladly merge those too :)

**Comment by Kalyanimhala** [comment]
Sure , Working on it!

**Comment by Kalyanimhala** [comment]
@Licenser , 
[simd-json-derive](https://github.com/simd-lite/simd-json/simd-json-derive) and the [value-trait](https://github.com/simd-lite/simd-json/value-trait) shows page not found!

**Comment by Licenser** [comment]
sorry, copy & pasta errors :)

https://github.com/simd-lite/simd-json-derive

https://github.com/simd-lite/value-trait

**Comment by Kalyanimhala** [comment]
Done for those two repos also! check and merge!
Thanks : )

**Pull request merged**
