### PR TITLE
Improve coverage #2

### PR DESCRIPTION
**Pull request by dvermd**
This PR is based on the PR #207 

- Add the ability to deserialize HashMaps from Tape.
- Add some more tests as part of #57
- Do not run coverage on test code

### CODE REVIEW

**Comment by dvermd** [comment]
It seems that the code coverage is tagged as decreased because it uses the number of lines as metrics. With the `--ignore-tests` option of tarpaulin, there are less lines that are to be covered. Looking at Coveralls report, we can that the `relevant` column decreased just like the `covered` one.

If you want to review this change in its own PR to better see the coverage improvements of the other commits, let me know and I'll split the PR.

**Comment by Licenser** [comment]
Sorry for the late reply :) this looks great I'll update the branch and see if that solves the clippy complaining

**Review by Licenser — APPROVED** [review]

**Comment by Licenser** [comment]
Seems update was not enough :) can you address the clippy issues and then  we can merge this :D

**Comment by dvermd** [comment]
I had a hard time finding the clippy warnings the previous commits added. So I fixed most of the clippy warnings (most of them by `clippy --fix`).
The only 2 remaining are from `json!` and `json_typed!` macro that swallow the error on inserting a (key, value) pair to a Value. I don't know how you want to handle this one but I think hiding the error this way will be misleading at some point for a user.

**Comment by Licenser** [comment]
:+1: awesome, I think leaving that out for now is fine. the `let _ = ...insert` in the macros isn't swallowing errors but rather swallowing the return value as we already know that the object is an object, and the content is a value since it's created by a macro :)

**Pull request merged**
