### PR TITLE
Allow the tape to be used in a standard serde::Deserialize

### PR DESCRIPTION
**Pull request by bassmanitram**
Issue #365 

* The new `from_tape` method on the Deserializer allows a tape to be extracted from a Deserializer via `into_tape` and then be used to rebuild a Deserializer. It is marked as `unsafe` because no structure verification is performed - it is up to the caller to make sure that the tape is correct (e.g. by extracting from a Deserializer, performing read-only operations, then rebuilding a Deserializer).

At the moment, however, nothing I try is able to allow access to that from within a standard serde::Deserializer.

* Deserialize in a tap: really complex to implement
* Extension Trait - specialization not allowed
* ?

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
Looks good :) I was about to suggest that on the issue when you submitted the PR 👍  thanks a lot!

**Comment by Licenser** [comment]
Oh I just saw, it'll need a `cargo fmt` before passing the CI

**Comment by bassmanitram** [comment]
K, I'm on it

**Comment by bassmanitram** [comment]
Hold of merging for now - the larger goal is to figure out how to take the deserializer in a serde::de::Deserialize implementation's deserialize method, get the Tape from it, do my "type determinant" searches, then turn the Tape back into the deserializer and pass it onto the discovered types. Obviously this PR enables that last bit, but it's getting the Tape from the "anonymous" deserializer that has me a bit stuck at the moment.

**Comment by Licenser** [comment]
I think  a way of achieving this would be changing the implementation from `Deserializer for Deserializer` (yay naming ...) to `Deserilizer for &[Node]` or `Deserializer for Vec<Node>` that way the same implementation would work for `Deserializer` and `Tape` since both have the vec/slice?

**Comment by bassmanitram** [comment]
Since Deserialize is foreign and so are Vec and any slice notation, we need a local Trait to cover them... thinking

**Comment by bassmanitram** [comment]
Ok, that's totally untested at the moment, but compiles and passes clippy - I'm now going to see if, at least in my use case, it works.

**Comment by bassmanitram** [comment]
You live and learn eh - can't "specialize", it seems - the default implementation is always invoked!

**Comment by bassmanitram** [comment]
OK, lets try a deserializer for Node ... which of course means I have to start hacking another of your libraries - value_trait :)

**Comment by bassmanitram** [comment]
Nope - that's fantastically complex too, it seems! This is becoming soul destroying!

**Comment by Licenser** [comment]
Just a few thought experiments would any of the following work:

1) move the implementation of `serde::Deserializer` from `simd_json::Deserializer` to `simd_json::Tape`
2) change the according functions that use the `deserializer.deserialize()` call to call `deserializer.into_tape().deseriaze()`

Or:

adding a `as_tape(&self)  -> &[Node]` function and use that to inspect the type

**Comment by bassmanitram** [comment]
OK, I leave this here - serde::de::DeserializeSeed "solves" the issue, but where I'm trying to implement it has serde_json so ingrained that swapping over to simd_json (with necessary "unsafe" stuff too) is just too onerous at the moment.

So the PR with only from_tape is ready, and some kind of solution to RawValue would be appreciated in the future.

**Review by Licenser — APPROVED** [review]

**Comment by Licenser** [comment]
I manually merged this to avoid the conflicts :) thank you!

**Pull request closed without merging**
