### PR TITLE
Use non-beta rustup as the OOM issue has been fixed.

### PR DESCRIPTION
**Pull request by hkratz**

### CODE REVIEW

**Comment by hkratz** [comment]
Hmm, apparently Rustup was **not** yet updated in the GH environment, so we need to wait a bit until it is.

**Comment by hkratz** [comment]
Waiting for https://github.com/actions/virtual-environments/issues/3418

**Comment by Licenser** [comment]
Makes sens :)

**Comment by hkratz** [comment]
Rustup has been updated in the Github CI images, so this can be merged now.

**Review by Licenser — APPROVED** [review]

**Pull request merged**
