### PR TITLE
Sync utf8 validation with upstream (lookup4)

### PR DESCRIPTION
**Pull request by CJP10**
closes https://github.com/simd-lite/simd-json/issues/98

### CODE REVIEW

**Comment by CJP10** [comment]
@Licenser I've ported the algorithm but haven't done any of the plumbing inside utf8check. Do you have an idea of how we could do the plumbing?

**Comment by Licenser** [comment]
Sorry about the late reply, it's been a bit crazy lately, I've not forgotten this just not gotten time to look into it, sorry!

**Comment by Licenser** [comment]
I think this is where we would want to hook in: https://github.com/simd-lite/simd-json/blob/main/src/avx2/stage1.rs#L88 (same for `sse4`) that should be pretty stirght forward I hope.

**Comment by CJP10** [comment]
@Licenser I think I plumbed everything together right. If you wouldn't mind giving it a quick review, if it looks good I can try and do the arm (neon) impl although I don't have an arm setup to test so might have to use CI a bit :smile:.

**Review by Licenser — APPROVED** [review]
Looks great code wise, I like the improved structure! It does improve the perf a bit :) yay! Thank you so much! <3

added throughput measurements:

### main
```
                                DOM                  STRUCT
======= simd-json ======== parse|stringify ===== parse|stringify ====
data/canada.json         410 MB/s   410 MB/s   680 MB/s   320 MB/s
data/citm_catalog.json   880 MB/s   520 MB/s  1490 MB/s  1170 MB/s
data/twitter.json        860 MB/s   690 MB/s  1060 MB/s  1540 MB/s
```

### lookup4
```
                                DOM                  STRUCT
======= simd-json ======== parse|stringify ===== parse|stringify ====
data/canada.json         410 MB/s   410 MB/s   680 MB/s   320 MB/s
data/citm_catalog.json   890 MB/s   520 MB/s  1500 MB/s  1170 MB/s
data/twitter.json        870 MB/s   690 MB/s  1080 MB/s  1530 MB/s
```

**Comment by Licenser** [comment]
ARM is somewhat broken at the moment, rust still changes frequently on that and it seems to go out of sync :(, in the end it's nightly only for now. I'm fine with merging it w/o an ARM update it's already a nice improvement :) but I'll leave that up to you, if you want to give ARM a go :+1: if not :+1: if you want to split it out in it's own PR :+1:

**Comment by CJP10** [comment]
Let's merge this then because ARM looks like another can of worms.

**Comment by Licenser** [comment]
Just needs some Clippy love and then it's ready to go :)

**Comment by CJP10** [comment]
Been busy and lazy 😆 . I'll clean up the lints in the next couple days.

**Comment by Licenser** [comment]
No hurry :) I very much know the feeling! just wanted to make sure we're not in a waiting deadlock ;)

**Comment by CJP10** [comment]
Yep :+1: . Looks like the remaining lint is about function size I might just allow it :smile:.

**Comment by CJP10** [comment]
@Licenser good to merge?

**Review by Licenser — APPROVED** [review]
👍 great work, thanks!

**Pull request merged**
