### PR TITLE
Added fallback function for CPUs that don't support pclmulqdq instructions

### LINKED ISSUE #202: Remove hard dependency on `pclmulqdq` support
Followup to #200.

We should have a fallback for replacing `_mm_clmulepi64_si128` on CPUs that do not support `pclmulqdq`  this could be done by making a fallback implementation for `compute_quote_mask`

### PR DESCRIPTION
**Pull request by superblaubeere27**
I was unable to create a faster function with SIMD instructions, primarily because x86 has no 64-bit vector multiply instruction. 

On my machine, the fallback function makes the parsing ~10% slower

Fixes #202

### CODE REVIEW

**Comment by Licenser** [comment]
Awesome :D code looks great! Thank you so much for the quick fix of the `pclmulqdq` issue :). It will just need a `cargo fmt --all` to make clippy happy I think otherwise :+1: ready to merge and I'll release a `0.4.8` with it

**Comment by Licenser** [comment]
Looks nice :+1: it seems to need a rebase to solve conflicts before we can merge it :)

**Comment by superblaubeere27** [comment]
> 
> 
> Looks nice 👍 it seems to need a rebase to solve conflicts before we can merge it :)

I can't find any merge conflicts. Or would that fix the Coverage QA failing?

**Comment by Licenser** [comment]
No the coverage is a different topic, but GH claims there is  a conflict with main and prohibits merging:

grafik

**Review by Licenser — APPROVED** [review]
looks great :D thank you!

**Pull request merged**
